# -*- coding: utf-8 -*-
"""Misinformation Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gksi2Z3_9xNAPcwOwrsMhjxhS4npJg4j
"""

!wget https://www.cs.ucsb.edu/~william/data/liar_dataset.zip

!unzip -o liar_dataset.zip

!ls

# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FdmpPTKpTfGK_bpaQq51CE8uUzQtb5G9
"""

!pip install gradio scikit-learn

import gradio as gr
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

# Sample training data
texts = [
    "The earth revolves around the sun",
    "Vaccines contain tracking microchips",
    "Water freezes at zero degrees Celsius",
    "5G towers spread viruses",
    "Exercise improves cardiovascular health",
    "The moon is made of cheese",
    "Doctors recommend balanced diets",
    "Climate change is a hoax"
]

labels = [
    "Truthful",
    "Misleading",
    "Truthful",
    "Misleading",
    "Truthful",
    "Misleading",
    "Truthful",
    "Misleading"
]

# Train ML model
model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('classifier', LogisticRegression())
])

model.fit(texts, labels)

# Rule-based detection
def rule_based_detection(text):
    keywords = ["hoax", "microchip", "virus", "fake", "conspiracy"]

    text = text.lower()

    for word in keywords:
        if word in text:
            return "Misleading"

    return "Truthful"

# Main prediction function
def analyse_text(text):

    rule_result = rule_based_detection(text)

    ml_prediction = model.predict([text])[0]
    confidence = model.predict_proba([text]).max() * 100

    final_result = (
        "Misleading"
        if rule_result == "Misleading" or ml_prediction == "Misleading"
        else "Truthful"
    )

    return f"""
Rule-Based Detection: {rule_result}

Machine Learning Prediction: {ml_prediction}

Confidence Score: {confidence:.2f}%

Final Classification: {final_result}
"""

# Gradio interface
interface = gr.Interface(
    fn=analyse_text,
    inputs=gr.Textbox(lines=5, placeholder="Enter text here..."),
    outputs="text",
    title="Detecting Digital Deception",
    description="Prototype misinformation detection system using rule-based and machine learning approaches."
)

interface.launch(share=True)

import pandas as pd

# Column names for the original LIAR dataset
columns = [
    "id",
    "label",
    "statement",
    "subject",
    "speaker",
    "speaker_job",
    "state",
    "party",
    "barely_true_count",
    "false_count",
    "half_true_count",
    "mostly_true_count",
    "pants_fire_count",
    "context"
]

# Load the three official dataset splits
train_df = pd.read_csv(
    "train.tsv",
    sep="\t",
    header=None,
    names=columns
)

valid_df = pd.read_csv(
    "valid.tsv",
    sep="\t",
    header=None,
    names=columns
)

test_df = pd.read_csv(
    "test.tsv",
    sep="\t",
    header=None,
    names=columns
)

print("Training:", train_df.shape)
print("Validation:", valid_df.shape)
print("Testing:", test_df.shape)

print("Training labels:")
print(train_df["label"].value_counts())

print("\nValidation labels:")
print(valid_df["label"].value_counts())

print("\nTesting labels:")
print(test_df["label"].value_counts())

print(train_df[["label", "statement"]].head(10))

# Map LIAR's six labels to the two categories used by our system

label_mapping = {
    "true": "Truthful",
    "mostly-true": "Truthful",
    "half-true": "Misleading",
    "barely-true": "Misleading",
    "false": "Misleading",
    "pants-fire": "Misleading"
}

train_df["binary_label"] = train_df["label"].map(label_mapping)
valid_df["binary_label"] = valid_df["label"].map(label_mapping)
test_df["binary_label"] = test_df["label"].map(label_mapping)

# Check the new distribution
print("Training:")
print(train_df["binary_label"].value_counts())

print("\nValidation:")
print(valid_df["binary_label"].value_counts())

print("\nTesting:")
print(test_df["binary_label"].value_counts())

# Check for missing statements
print("Missing training statements:", train_df["statement"].isna().sum())
print("Missing validation statements:", valid_df["statement"].isna().sum())
print("Missing testing statements:", test_df["statement"].isna().sum())

# Display a few statements
print("\nExample statements:")
for i, text in enumerate(train_df["statement"].head(5), start=1):
    print(f"{i}. {text}")

# Check the data types
print(train_df[["statement", "binary_label"]].dtypes)

!pip install nltk

import nltk

nltk.download("punkt")
nltk.download("stopwords")

import re
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words("english"))

def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)

    # Remove punctuation and special characters
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # Tokenise the text
    tokens = word_tokenize(text)

    # Remove English stop words
    tokens = [word for word in tokens if word not in stop_words]

    # Join tokens back into a single string
    processed_text = " ".join(tokens)

    return processed_text

import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

test_statements = train_df["statement"].head(5)

for i, statement in enumerate(test_statements, start=1):
    print(f"Statement {i}:")
    print("Original :", statement)
    print("Processed:", preprocess_text(statement))
    print("-" * 80)

# Apply preprocessing to all dataset splits

train_processed = train_df["statement"].apply(preprocess_text)
valid_processed = valid_df["statement"].apply(preprocess_text)
test_processed = test_df["statement"].apply(preprocess_text)

print("Training processed:", train_processed.shape)
print("Validation processed:", valid_processed.shape)
print("Testing processed:", test_processed.shape)

# Compare original and processed statements

for i in range(5):
    print(f"Statement {i + 1}")
    print("Original :", train_df["statement"].iloc[i])
    print("Processed:", train_processed.iloc[i])
    print("-" * 80)

from sklearn.feature_extraction.text import TfidfVectorizer

# Create the TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Learn the vocabulary and calculate TF-IDF values
# using the training data only
X_train = tfidf_vectorizer.fit_transform(train_processed)

print("Training TF-IDF shape:", X_train.shape)

# Transform validation and test data
# using the vocabulary learned from the training data

X_valid = tfidf_vectorizer.transform(valid_processed)
X_test = tfidf_vectorizer.transform(test_processed)

print("Training TF-IDF shape:", X_train.shape)
print("Validation TF-IDF shape:", X_valid.shape)
print("Testing TF-IDF shape:", X_test.shape)

# Create the target labels for each dataset split

y_train = train_df["binary_label"]
y_valid = valid_df["binary_label"]
y_test = test_df["binary_label"]

print("Training labels:", y_train.shape)
print("Validation labels:", y_valid.shape)
print("Testing labels:", y_test.shape)

from sklearn.linear_model import LogisticRegression

# Create the Logistic Regression classifier
ml_model = LogisticRegression(max_iter=1000)

# Train the model using the training TF-IDF features
ml_model.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

# Make predictions on the validation dataset

valid_predictions = ml_model.predict(X_valid)

print("First 10 validation predictions:")
print(valid_predictions[:10])

from sklearn.metrics import accuracy_score

# Calculate validation accuracy
valid_accuracy = accuracy_score(y_valid, valid_predictions)

print(f"Validation Accuracy: {valid_accuracy * 100:.2f}%")

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Evaluate the ML model on the validation set
valid_predictions = ml_model.predict(X_valid)

print("Validation Accuracy:")
print(f"{accuracy_score(y_valid, valid_predictions) * 100:.2f}%")

print("\nClassification Report:")
print(classification_report(y_valid, valid_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_valid, valid_predictions))

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Improved Logistic Regression model
balanced_ml_model = LogisticRegression(
    class_weight="balanced",
    max_iter=1000
)

# Train using the existing TF-IDF training features
balanced_ml_model.fit(X_train, y_train)

# Predict on the validation set
balanced_predictions = balanced_ml_model.predict(X_valid)

# Evaluate
print("Balanced Logistic Regression Validation Accuracy:")
print(f"{accuracy_score(y_valid, balanced_predictions) * 100:.2f}%")

print("\nClassification Report:")
print(classification_report(y_valid, balanced_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_valid, balanced_predictions))

# Apply the preprocessing function to the statement column

train_df["processed_statement"] = train_df["statement"].apply(preprocess_text)
valid_df["processed_statement"] = valid_df["statement"].apply(preprocess_text)
test_df["processed_statement"] = test_df["statement"].apply(preprocess_text)

# Check that the new columns were created
print(train_df[["statement", "processed_statement"]].head())

print(train_df.columns.tolist())

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# TF-IDF using unigrams and bigrams
bigram_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2)
)

# Fit only on the training data
X_train_bigram = bigram_vectorizer.fit_transform(train_df["processed_statement"])

# Transform validation data using the same fitted vectorizer
X_valid_bigram = bigram_vectorizer.transform(valid_df["processed_statement"])

print("Training feature shape:", X_train_bigram.shape)
print("Validation feature shape:", X_valid_bigram.shape)

# Balanced Logistic Regression
bigram_ml_model = LogisticRegression(
    class_weight="balanced",
    max_iter=1000
)

# Train
bigram_ml_model.fit(X_train_bigram, y_train)

# Predict validation data
bigram_predictions = bigram_ml_model.predict(X_valid_bigram)

# Evaluate
print("\nTF-IDF + Bigrams + Balanced Logistic Regression")
print(f"Validation Accuracy: {accuracy_score(y_valid, bigram_predictions) * 100:.2f}%")

print("\nClassification Report:")
print(classification_report(y_valid, bigram_predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_valid, bigram_predictions))

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Controlled TF-IDF using unigrams and bigrams
controlled_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    max_features=30000
)

# Fit only on training data
X_train_controlled = controlled_vectorizer.fit_transform(
    train_df["processed_statement"]
)

# Transform validation data
X_valid_controlled = controlled_vectorizer.transform(
    valid_df["processed_statement"]
)

print("Training feature shape:", X_train_controlled.shape)
print("Validation feature shape:", X_valid_controlled.shape)

# Balanced Logistic Regression
controlled_ml_model = LogisticRegression(
    class_weight="balanced",
    max_iter=1000
)

controlled_ml_model.fit(
    X_train_controlled,
    y_train
)

# Validation prediction
controlled_predictions = controlled_ml_model.predict(
    X_valid_controlled
)

print("\nControlled TF-IDF + Balanced Logistic Regression")
print(
    f"Validation Accuracy: "
    f"{accuracy_score(y_valid, controlled_predictions) * 100:.2f}%"
)

print("\nClassification Report:")
print(
    classification_report(
        y_valid,
        controlled_predictions
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_valid,
        controlled_predictions
    )
)

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Linear Support Vector Machine
svm_model = LinearSVC(
    class_weight="balanced"
)

# Train using the full unigram + bigram TF-IDF features
svm_model.fit(
    X_train_bigram,
    y_train
)

# Predict validation data
svm_predictions = svm_model.predict(
    X_valid_bigram
)

# Evaluate
print("TF-IDF + Bigrams + Balanced Linear SVM")
print(
    f"Validation Accuracy: "
    f"{accuracy_score(y_valid, svm_predictions) * 100:.2f}%"
)

print("\nClassification Report:")
print(
    classification_report(
        y_valid,
        svm_predictions
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_valid,
        svm_predictions
    )
)

# Check how the model distributed its predictions

print("Validation prediction distribution:")
print(pd.Series(valid_predictions).value_counts())

import re

def rule_based_detection(text):
    # Patterns associated with potentially misleading claims
    rules = {
        "conspiracy_language": [
            r"\bconspiracy\b",
            r"\bthey are hiding\b",
            r"\bhidden truth\b",
            r"\bsecretly\b"
        ],

        "deceptive_claims": [
            r"\bfake news\b",
            r"\bhoax\b",
            r"\bfalse information\b",
            r"\blie\b"
        ],

        "sensational_language": [
            r"\bshocking\b",
            r"\bshocking truth\b",
            r"\bno one is telling\b",
            r"\bexposed\b"
        ]
    }

    text = text.lower()

    triggered_rules = []

    # Check each rule category
    for category, patterns in rules.items():
        for pattern in patterns:
            if re.search(pattern, text):
                triggered_rules.append(category)
                break

    # Classify based on whether any rules were triggered
    if triggered_rules:
        result = "Misleading"
    else:
        result = "Truthful"

    return result, triggered_rules

test_rule_statements = [
    "This is fake news.",
    "The government is secretly hiding the truth.",
    "The earth revolves around the sun.",
    "Exercise improves cardiovascular health.",
    "This shocking truth has been exposed."
]

for statement in test_rule_statements:
    result, rules_triggered = rule_based_detection(statement)

    print("Statement:", statement)
    print("Classification:", result)
    print("Rules triggered:", rules_triggered)
    print("-" * 80)

for i, statement in enumerate(train_df["statement"].head(10), start=1):
    result, rules_triggered = rule_based_detection(statement)

    print(f"Statement {i}:")
    print("Original:", statement)
    print("Classification:", result)
    print("Rules triggered:", rules_triggered)
    print("-" * 80)

import re

def rule_based_detection(text):
    rules = {
        "conspiracy_language": [
            r"\bconspiracy\b",
            r"\bthey are hiding\b",
            r"\bhidden truth\b",
            r"\bsecretly\b",
            r"\bcover.?up\b",
            r"\bthey don't want you to know\b",
            r"\bwhat they aren't telling you\b",
            r"\bhidden agenda\b"
        ],

        "deceptive_claims": [
            r"\bfake news\b",
            r"\bhoax\b",
            r"\bfalse information\b",
            r"\bfabricated\b",
            r"\blie\b",
            r"\bcompletely false\b",
            r"\bmade up\b",
            r"\bnot true\b",
            r"\bfalse claim\b",
            r"\bfalse claims\b"
        ],

        "sensational_language": [
            r"\bshocking\b",
            r"\bshocking truth\b",
            r"\bno one is telling\b",
            r"\byou won't believe\b",
            r"\bexposed\b",
            r"\bunbelievable\b",
            r"\boutrageous\b"
        ],

        "absolute_claims": [
            r"\balways\b",
            r"\bnever\b",
            r"\beveryone\b",
            r"\bnobody\b",
            r"\bno one\b",
            r"\b100%\b",
            r"\ball of\b",
            r"\bnone of\b",
            r"\bwithout exception\b"
        ],

        "strong_certainty": [
            r"\bdefinitely\b",
            r"\bcertainly\b",
            r"\bthere is no doubt\b",
            r"\bproves that\b",
            r"\bguaranteed\b",
            r"\bundeniably\b",
            r"\bproven\b",
            r"\bbeyond doubt\b"
        ]
    }

    # Convert text to lowercase
    text = text.lower()

    triggered_rules = []
    score = 0

    # Check each rule category
    for category, patterns in rules.items():
        category_triggered = False

        for pattern in patterns:
            if re.search(pattern, text):
                category_triggered = True
                break

        if category_triggered:
            triggered_rules.append(category)

            # Assign category weights
            if category in ["conspiracy_language", "deceptive_claims"]:
                score += 2
            else:
                score += 1

    # Maximum possible score
    max_score = 7

    # Convert score into a rule-based risk percentage
    risk_percentage = (score / max_score) * 100

    # Classification threshold
    if score >= 2:
        result = "Misleading"
    else:
        result = "Truthful"

    return result, score, risk_percentage, triggered_rules

test_rule_statements = [
    "This is fake news.",
    "The government is secretly hiding the truth.",
    "The earth revolves around the sun.",
    "Exercise improves cardiovascular health.",
    "This shocking truth has been exposed.",
    "Everyone knows that this is definitely true."
]

for statement in test_rule_statements:
    result, score, risk_percentage, rules_triggered = rule_based_detection(statement)

    print("Statement:", statement)
    print("Classification:", result)
    print("Risk Score:", score)
    print(f"Rule-Based Risk: {risk_percentage:.2f}%")
    print("Rules triggered:", rules_triggered)
    print("-" * 80)

for i, statement in enumerate(train_df["statement"].head(10), start=1):
    result, score, risk_percentage, rules_triggered = rule_based_detection(statement)

    print(f"Statement {i}:")
    print("Original:", statement)
    print("Classification:", result)
    print("Risk Score:", score)
    print(f"Rule-Based Risk: {risk_percentage:.2f}%")
    print("Rules triggered:", rules_triggered)
    print("-" * 80)

print(rule_based_detection("Climate change is a fake conspiracy created to manipulate the global economy."))

print(rule_based_detection(
    "Cybersecurity experts advise users to enable two-factor authentication to improve account security."
))

print(rule_based_detection.__code__.co_consts)

truthful_example = (
    "Cybersecurity experts advise users to enable "
    "two-factor authentication to improve account security."
)

misleading_example = (
    "Climate change is a fake conspiracy created "
    "to manipulate the global economy."
)

print("Truthful example:")
print(rule_based_detection(truthful_example))

print("\nMisleading example:")
print(rule_based_detection(misleading_example))

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Apply rule-based detection to the validation statements
rule_predictions = []

for text in valid_df["statement"]:
    result, score, risk_percentage, triggered_rules = rule_based_detection(text)
    rule_predictions.append(result)

# Evaluate the rule-based system
print("Rule-Based Validation Accuracy:")
print(f"{accuracy_score(y_valid, rule_predictions) * 100:.2f}%")

print("\nClassification Report:")
print(
    classification_report(
        y_valid,
        rule_predictions
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_valid,
        rule_predictions
    )
)

from collections import Counter

rule_scores = []
rule_results = []

for text in valid_df["statement"]:
    result, score, risk_percentage, triggered_rules = rule_based_detection(text)

    rule_scores.append(score)
    rule_results.append(result)

print("Rule Score Distribution:")
print(Counter(rule_scores))

print("\nNumber of statements triggering at least one rule:")
print(sum(score > 0 for score in rule_scores))

print("\nNumber of statements classified as Misleading:")
print(sum(result == "Misleading" for result in rule_results))

truthful_example = (
    "Cybersecurity experts advise users to enable "
    "two-factor authentication to improve account security."
)

misleading_example = (
    "Climate change is a fake conspiracy created "
    "to manipulate the global economy."
)

print("Truthful example:")
print(rule_based_detection(truthful_example))

print("\nMisleading example:")
print(rule_based_detection(misleading_example))

rule_predictions = []

for text in valid_df["statement"]:
    result, score, risk_percentage, triggered_rules = rule_based_detection(text)
    rule_predictions.append(result)

print("Improved Rule-Based Validation Accuracy:")
print(f"{accuracy_score(y_valid, rule_predictions) * 100:.2f}%")

print("\nClassification Report:")
print(
    classification_report(
        y_valid,
        rule_predictions
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_valid,
        rule_predictions
    )
)

from collections import Counter

category_counts = Counter()

for text in valid_df["statement"]:
    result, score, risk_percentage, triggered_rules = rule_based_detection(text)

    for rule in triggered_rules:
        category_counts[rule] += 1

print("Rule Category Frequencies:")
for category, count in category_counts.most_common():
    print(f"{category}: {count}")

def final_prediction(text):

    # -----------------------------
    # Rule-Based Analysis
    # -----------------------------
    rule_result, rule_score, rule_risk, triggered_rules = (
        rule_based_detection(text)
    )

    # -----------------------------
    # ML Analysis
    # -----------------------------
    text_features = tfidf_vectorizer.transform([text])

    ml_prediction = ml_model.predict(text_features)[0]

    ml_probabilities = ml_model.predict_proba(text_features)[0]

    misleading_index = list(ml_model.classes_).index("Misleading")

    ml_misleading_probability = (
        ml_probabilities[misleading_index] * 100
    )

    ml_confidence = ml_probabilities.max() * 100

    # -----------------------------
    # Final Classification
    # -----------------------------
    final_result = ml_prediction

    # -----------------------------
    # Format Rule Indicators
    # -----------------------------
    if triggered_rules:
        indicators = ", ".join(
            rule.replace("_", " ").title()
            for rule in triggered_rules
        )
    else:
        indicators = "None detected"

    return (
        f"Final Classification: {final_result}\n\n"
        f"ML Prediction: {ml_prediction}\n"
        f"ML Confidence: {ml_confidence:.2f}%\n"
        f"ML Misleading Probability: "
        f"{ml_misleading_probability:.2f}%\n\n"
        f"Rule-Based Result: {rule_result}\n"
        f"Rule-Based Risk: {rule_risk:.2f}%\n"
        f"Detected Indicators: {indicators}"
    )

test_text = (
    "Cybersecurity experts advise users to enable "
    "two-factor authentication to improve account security."
)

result = final_prediction(test_text)

print(result)

test_text = (
    "Climate change is a fake conspiracy created "
    "to manipulate the global economy."
)

result = final_prediction(test_text)

print(result)

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Store hybrid predictions
hybrid_predictions = []

# Store hybrid scores
hybrid_scores = []

for text in valid_df["statement"]:

    # Rule-based result
    rule_result, rule_score, rule_risk, triggered_rules = (
        rule_based_detection(text)
    )

    # Convert text using the SAME TF-IDF vectorizer
    text_features = tfidf_vectorizer.transform([text])

    # ML probability
    ml_probabilities = ml_model.predict_proba(text_features)[0]

    # Find probability of Misleading
    misleading_index = list(ml_model.classes_).index("Misleading")
    ml_misleading_probability = (
        ml_probabilities[misleading_index] * 100
    )

    # Hybrid score
    hybrid_score = (
        0.5 * rule_risk +
        0.5 * ml_misleading_probability
    )

    hybrid_scores.append(hybrid_score)

    # Final classification
    if hybrid_score >= 50:
        final_result = "Misleading"
    else:
        final_result = "Truthful"

    hybrid_predictions.append(final_result)


# Evaluate hybrid system
print("Hybrid Model Validation Accuracy:")
print(
    f"{accuracy_score(y_valid, hybrid_predictions) * 100:.2f}%"
)

print("\nClassification Report:")
print(
    classification_report(
        y_valid,
        hybrid_predictions
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_valid,
        hybrid_predictions
    )
)

# Rule-assisted ML predictions

rule_assisted_predictions = []

for text in valid_df["statement"]:

    # Rule-based detection
    rule_result, rule_score, rule_risk, triggered_rules = (
        rule_based_detection(text)
    )

    # ML features
    text_features = tfidf_vectorizer.transform([text])

    # ML prediction
    ml_prediction = ml_model.predict(text_features)[0]

    # Rule-assisted decision
    if ml_prediction == "Misleading":
        final_result = "Misleading"

    elif rule_score >= 4:
        final_result = "Misleading"

    else:
        final_result = "Truthful"

    rule_assisted_predictions.append(final_result)


print("Rule-Assisted ML Validation Accuracy:")
print(
    f"{accuracy_score(y_valid, rule_assisted_predictions) * 100:.2f}%"
)

print("\nClassification Report:")
print(
    classification_report(
        y_valid,
        rule_assisted_predictions
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_valid,
        rule_assisted_predictions
    )
)

test_text = (
    "Climate change is a fake conspiracy created "
    "to manipulate the global economy."
)

print(final_prediction(test_text))

test_text = (
    "Cybersecurity experts advise users to enable "
    "two-factor authentication to improve account security."
)

print(final_prediction(test_text))

import gradio as gr


def analyse_statement(text):

    if not text or not text.strip():
        return "Please enter a statement to analyse."

    result = final_prediction(text)

    return result


interface = gr.Interface(
    fn=analyse_statement,

    inputs=gr.Textbox(
        lines=6,
        placeholder="Enter a statement to analyse...",
        label="Statement"
    ),

    outputs=gr.Textbox(
        lines=10,
        label="Analysis Results"
    ),

    title="Detecting Digital Deception",

    description=(
        "A misinformation detection prototype "
        "using TF-IDF, Logistic Regression, and "
        "rule-based linguistic analysis."
    ),

    examples=[
        [
            "Over the last 10 years, incomes for the top 1 percent "
            "have grown. Meanwhile, the bottom half of the country, "
            "theyve seen their wages stagnate."
        ],
        [
            "Climate change is a fake conspiracy created "
            "to manipulate the global economy."
        ]
    ]
)

interface.launch(share=True)
