# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FdmpPTKpTfGK_bpaQq51CE8uUzQtb5G9
"""

!pip install gradio scikit-learn

import gradio as gr
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

# Sample training data
texts = [
    "The earth revolves around the sun",
    "Vaccines contain tracking microchips",
    "Water freezes at zero degrees Celsius",
    "5G towers spread viruses",
    "Exercise improves cardiovascular health",
    "The moon is made of cheese",
    "Doctors recommend balanced diets",
    "Climate change is a hoax"
]

labels = [
    "Truthful",
    "Misleading",
    "Truthful",
    "Misleading",
    "Truthful",
    "Misleading",
    "Truthful",
    "Misleading"
]

# Train ML model
model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('classifier', LogisticRegression())
])

model.fit(texts, labels)

# Rule-based detection
def rule_based_detection(text):
    keywords = ["hoax", "microchip", "virus", "fake", "conspiracy"]

    text = text.lower()

    for word in keywords:
        if word in text:
            return "Misleading"

    return "Truthful"

# Main prediction function
def analyse_text(text):

    rule_result = rule_based_detection(text)

    ml_prediction = model.predict([text])[0]
    confidence = model.predict_proba([text]).max() * 100

    final_result = (
        "Misleading"
        if rule_result == "Misleading" or ml_prediction == "Misleading"
        else "Truthful"
    )

    return f"""
Rule-Based Detection: {rule_result}

Machine Learning Prediction: {ml_prediction}

Confidence Score: {confidence:.2f}%

Final Classification: {final_result}
"""

# Gradio interface
interface = gr.Interface(
    fn=analyse_text,
    inputs=gr.Textbox(lines=5, placeholder="Enter text here..."),
    outputs="text",
    title="Detecting Digital Deception",
    description="Prototype misinformation detection system using rule-based and machine learning approaches."
)

interface.launch(share=True)